### ISSUE TITLE
Official Amiga setnames

### ISSUE THREAD

**Issue by wizzomafizzo** [RGarciaLago/MGL_Core_Setnames#1]
I've noticed the AmigaVision project has defined their own setnames to split up the Amiga core such as `Amiga500`. I have also had requests from users to support setnames for `Amiga600` and `Amiga1200`. I think they could may be good candidates for new defined setnames

I'm not actually that familiar with the Amiga core myself. But maybe @limi could give some advice on if these are appropriate to include

**Comment by limi** [comment]
There are essentially only two configurations that make sense for most people:

**Amiga 500:** This is an MGL configured to use the 68000 processor, ECS chipset, and 512kB of expansion RAM. Useful for maximum compatibility with floppy disk image based games and demo scene productions.

**Amiga 1200:** This is the "unrestricted" Amiga that has plenty of RAM, uses the AGA chipset, 68020 processor and hard disks / CD-ROM. Best used with a hard-disk based setup like [AmigaVision](https://amiga.vision). We call this just "Amiga" in AmigaVision, since it kind of encapsulates all the Amigas, and also to make it clear that it's generally the one you should be using unless you have specific needs like the A500 configuration.

It's been a while since I've done a clean install of MiSTer, so I can't remember what the defaults are when starting the core with nothing configured, but I suspect it's closer to the A500 config.

Setups for Amiga 1000, 600, 3000, 500+ etc don't really make any sense, as there isn't really anything that only runs on these configurations. We include A500HD and A600HD (really an A3000) mostly for operating system nerds that want to set up these for historical/research purposes or for pure nostalgia, these aren't significant in any real way for the end user in 2023.

Feel free to grab our "Amiga" and "Amiga 500" MGLs, note that they will also need the corresponding config files to actually be different.

**Comment by wizzomafizzo** [comment]
@limi Thank you for explaining that so thoroughly. Makes total sense.

That's a tricky one then. I'm not sure if I could convince anyone to ship the AmigaVision configs to be honest. In that case this would just be confusing for the user. Maybe best to leave it up to the enthusiasts, and support it on my own.

I appreciate all the work AmigaVision does! It's an amazing project, even as someone who never had an Amiga
